-- CREATE TABLE profiles(
--   id VARCHAR(225) NOT NULL,
--   name VARCHAR(225) NOT NULL,
--   email VARCHAR(225) NOT NULL,
--   picture VARCHAR(225) NOT NULL,
--   PRIMARY KEY(email)
-- )

-- CREATE TABLE Keeps(
--   id int AUTO_INCREMENT,
--   creatorId VARCHAR(225) NOT NULL,
--   name VARCHAR(225) NOT NULL,
--   img VARCHAR(225) NOT NULL,
--   views INT,
--   shares INT,
--   keeps INT,
--   PRIMARY KEY (id)
-- )